on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN_PRD }}
          role-session-name: deploy
          aws-region: us-east-1
      - name: install
        run: pnpm i
      - name: build
        run: pnpm frontend build
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          BASE_URL: https://${{ secrets.DOMAIN }}/
          USE_DRAFT: 'false'
          GA_ID: ${{ secrets.GA_ID_PRD }}
          GOOGLE_ADSENSE_PUBLISHER_ID: ${{ secrets.GOOGLE_ADSENSE_PUBLISHER_ID }}
          GOOGLE_ADSENSE_SLOT_DISPLAY_HORIZONTAL: ${{ secrets.GOOGLE_ADSENSE_SLOT_DISPLAY_HORIZONTAL }}
          GOOGLE_ADSENSE_SLOT_MULTIPLEX_HORIZONTAL: ${{ secrets.GOOGLE_ADSENSE_SLOT_MULTIPLEX_HORIZONTAL }}
          GOOGLE_ADSENSE_SLOT_IN_FEED: ${{ secrets.GOOGLE_ADSENSE_SLOT_IN_FEED }}
          INQUIRY_GOOGLE_FORM_URL: ${{ secrets.INQUIRY_GOOGLE_FORM_URL_PRD }}
          IFRAMELY_PROXY_URL: ${{ secrets.IFRAMELY_PROXY_URL_PRD }}
      - name: Copy index.html to s3
        run: |
          aws s3 sync --delete --exclude '*.html' --exclude '*.txt' --exclude '*.xml' --exclude 'pagefind/*' ./out/ s3://${{ secrets.BUCKET_NAME_PRD }}/ --cache-control max-age=31536000,public
          aws s3 sync --delete --exclude '*' --include '*.html' --include '*.txt' --include '*.xml' --include 'pagefind/*' ./out/ s3://${{ secrets.BUCKET_NAME_PRD }}/ --cache-control no-cache
        working-directory: template
